// Code generated by hertz generator.

package main

import (
	"chat/common/logs"
	"chat/config"
	"chat/dal"
	"context"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	logs.Init()                    // 日志初始化
	config.Init()                  // 配置初始化
	dal.Init(context.Background()) // 数据库初始化

	register(h) // 注册路由
	h.Spin()
}
